# Generated by Django 4.0.6 on 2022-07-16 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('agencia', models.CharField(max_length=4)),
                ('numero', models.CharField(max_length=10)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='banco.cliente')),
            ],
        ),
    ]
