# Generated by Django 4.0.6 on 2022-07-17 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0002_cliente_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='senha',
            field=models.CharField(default='', max_length=255),
        ),
    ]
