# Generated by Django 4.0.6 on 2022-07-17 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0003_cliente_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_hora', models.DateTimeField(null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tipo', models.CharField(choices=[('DPST', 'Deposito'), ('SQUE', 'Saque'), ('TFRE', 'Transferencia_Recebida'), ('TFEN', 'Transferencia_Enviada')], max_length=5)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.conta')),
            ],
        ),
    ]
