# Generated by Django 4.0.6 on 2022-07-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0005_alter_transacao_data_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data_hora',
            field=models.DateTimeField(),
        ),
    ]
