# Generated by Django 4.0.6 on 2022-07-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0006_alter_transacao_data_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sobrenome',
            field=models.CharField(default='', max_length=150),
        ),
    ]
