# Generated by Django 4.0.6 on 2022-07-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0007_alter_cliente_nome_alter_cliente_sobrenome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sobrenome',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
